// Generated by https://quicktype.io

export interface RespLog {
    DataBeanProperties: RespLogDataBeanProperties;
    DataBeanName:       string;
}

export interface RespLogDataBeanProperties {
    Type:        number;
    ObjectValue: ObjectValue;
    ClassName:   string;
    Date:        string;
}

export interface ObjectValue {
    DataBeanProperties: ObjectValueDataBeanProperties;
    DataBeanName:       string;
}

export interface ObjectValueDataBeanProperties {
    msg:        string;
    Account:    Account;
    IDDocument: null;
    IDSession:  number;
    bloqueado:  boolean;
    MacAddress: string;
    IDAccount:  number;
    InitDate:   string;
    IDOffice:   number;
    Estado:     string;
    Type:       number;
    FinalDate:  null;
    LeftDate:   null;
    LeftValue:  null;
    State:      number;
    IPAddress:  string;
    HostName:   string;
}

export interface Account {
    DataBeanProperties: AccountDataBeanProperties;
    DataBeanName:       string;
}

export interface AccountDataBeanProperties {
    msg:            string;
    User:           null;
    EntityName:     string;
    PDF417Str:      null;
    IDFunctionalLn: number;
    Surname1:       string;
    Grade:          string;
    IDAccount:      number;
    RoleID:         number;
    eMail:          string;
    Active:         boolean;
    Nit:            number;
    Since:          string;
    cambiar:        boolean;
    Name1:          string;
    Age:            number;
    Password:       null;
}
