// Generated by https://quicktype.io

export interface RespProps {
    DataBeanProperties: RespPropsDataBeanProperties;
    DataBeanName:       string;
}
export interface RespProp {
    DataBeanProperties: RespPropsDataBeanProperty;
    DataBeanName:       string;
}
export interface RespPropsDataBeanProperties {
    Type:        number;
    ObjectValue: ObjectValue[] ;
    ClassName:   string;
    Date:        string;
}
export interface RespPropsDataBeanProperty{
    Type:        number;
    ObjectValue: ObjectValue;
    ClassName:   string;
    Date:        string;
}

export interface ObjectValue {
    DataBeanProperties: ObjectValueDataBeanProperties;
    DataBeanName:       string;
}

export interface ObjectValueDataBeanProperties {
    Nombre:        string;
    IDPropiedades: number;
    Since:         string;
    Descripcion:   string;
    Valor:         string;
    IDPerfilBanco: null;
    Estado:        number;
}
